/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package v3;

public class Constants {

  public static final String METRIC_TAG_APPID = "appid";

  public static final String METRIC_TAG_HOSTIP = "hostip";

  public static final String SERVICE_VERSION = "V2.0";

}
