/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package v2;


public enum MetricValueType implements org.apache.thrift.TEnum {
  TYPE_FLOAT(0),
  TYPE_LONG(1);

  private final int value;

  private MetricValueType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MetricValueType findByValue(int value) { 
    switch (value) {
      case 0:
        return TYPE_FLOAT;
      case 1:
        return TYPE_LONG;
      default:
        return null;
    }
  }
}
